# Instalación de SSH --
# yum –y install openssh-server openssh-clients
# systemctl start sshd
# systemctl enable sshd
# ----

# -- Instlación de Ansible --
# yum install epel-release
# yum install ansible
# yum -y update
# ----

# -- Generación de una clave SSH que punta al mismo ordenador --
# ssh-keygen
# Pulsa enter y introduce una frase.
# ssh-copy-id root@192.168.1.37
# vi /etc/ansible/hosts
# Añade la IP del ordenador al que quieres apuntar
# mkdir Ansible
# ----

# ansible-galaxy collection install community.crypto

# Instalación de Harbor en Centos 7
---

- name: Instalacion de Harbor
  hosts: servidor
  tasks:

  - name: Instalando Wget
    yum:
      name: wget
      state: present

  - name: Creando el directorio para Harbor
    shell: mkdir -p /Harbor

  - name: Descargando Harbor
    shell: chdir=/Harbor wget -nc https://github.com/vmware/harbor/releases/download/v1.2.0/harbor-online-installer-v1.2.0.tgz

  - name: Descomprimiendo la descarga de Harbor
    shell: chdir=/Harbor tar -xvf harbor-online-installer-v1.2.0.tgz

  - name: Creando un directorio para el certificado propio
    shell: mkdir -p /Harbor/Certificados

  - name: Creando el certificado propio
    shell: chdir=/Harbor/Certificados openssl req -sha256 -x509 -days 365 -nodes -newkey rsa:4096 -keyout  harbor.entorno.com.key -out harbor.entorno.com.crt -subj "/C=ES/ST=Spain/L=Valencia/O=Dybbukk/OU=DevOps/CN=harbor.entorno.com"

  - name: Se crea un enlace simbolico
    shell: chdir=/Harbor/Certificados ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    ignore_errors: yes

  - name: Modificando el hostname de Harbor
    ansible.builtin.lineinfile:
      path: /Harbor/harbor/harbor.cfg
      regexp: '^(.*)hostname = reg.mydomain.com(.*)$'
      line: 'hostname=harbor.entorno.com'
      backrefs: yes

  - name: Indicando a Harbor que utilice https
    ansible.builtin.lineinfile:
      path: /Harbor/harbor/harbor.cfg
      regexp: '^(.*)ui_url_protocol = http(.*)$'
      line: 'ui_url_protocol = https'
      backrefs: yes

  - name: Indicando a Harbor donde esta el certificado
    ansible.builtin.lineinfile:
      path: /Harbor/harbor/harbor.cfg
      regexp: '^(.*)ssl_cert = /data/cert/server.crt(.*)$'
      line: 'ssl_cert = /Harbor/Certificados/harbor.entorno.com.crt'
      backrefs: yes

  - name: Indicando a Harbor donde esta el certificado
    ansible.builtin.lineinfile:
      path: /Harbor/harbor/harbor.cfg
      regexp: '^(.*)ssl_cert_key = /data/cert/server.key(.*)$'
      line: 'ssl_cert_key = /Harbor/Certificados/harbor.entorno.com.key'
      backrefs: yes

  - name: Cambiando contraseña de la BD de Harbor I
    ansible.builtin.lineinfile:
      path: /Harbor/harbor/harbor.cfg
      regexp: '^(.*)db_password = root123(.*)$'
      line: 'db_password = {{ HARBOR_PASS }}'
      backrefs: yes

  - name: Cambiando contraseña le la BD de Harbor II
    ansible.builtin.lineinfile:
      path: /Harbor/harbor/harbor.cfg
      regexp: '^(.*)clair_db_password = password(.*)$'
      line: 'clair_db_password = {{ HARBOR_PASS }}'
      backrefs: yes

  - name: Cambiando contraseña le la BD de Harbor III
    ansible.builtin.lineinfile:
      path: /Harbor/harbor/harbor.cfg
      regexp: '^(.*)harbor_admin_password = Harbor12345(.*)$'
      line: 'harbor_admin_password = {{ HARBOR_PASS }}'
      backrefs: yes

  - name: Ejecutando el Script de Harbor
    shell: chdir=/Harbor/harbor ./install.sh

  - name: Instalando Harbor con Docker-Compose
    shell: chdir=/Harbor/harbor docker-compose up -d

  - name: Habilitando el puerto 80
    shell: firewall-cmd --permanent --zone=public --add-port=80/tcp

  - name: Reiniciando el firewall
    shell: firewall-cmd --reload

  - name: Configurando el DNS
    ansible.builtin.lineinfile:
      path: /etc/hosts
      line: "{{ HARBOR_IP }}\tharbor.entorno.com"
      state: present

  - name: Añadiendo la IP del servidor HARBOR al JSON
    copy:
      dest: /etc/docker/daemon.json
      content: |
        {"insecure-registries":["{{ HARBOR_IP }}:80"]}

  - name: Añadiendo la direccion a OpenSSL
    ansible.builtin.lineinfile:
      path: /etc/pki/tls/openssl.cnf
      insertafter: '# Extensions for a typical CA'
      line: "subjectAltName=DNS:harbor.entorno.com,IP:{{ HARBOR_IP }}"

  - name: Creando el directorio para el certificado de Docker I
    shell: mkdir -p /etc/docker/certs.d/harbor.entorno.com:80

  - name: Creando el directorio para el certificado de Docker II
    shell: mkdir -p /etc/docker/certs.d/harbor.entorno.com

  - name: Copiando el certificado I
    shell: cp -u /Harbor/Certificados/harbor.entorno.com.crt /etc/docker/certs.d/harbor.entorno.com:80/harbor.entorno.com.crt

  - name: Copiando el certificado II
    shell: cp -u /Harbor/Certificados/harbor.entorno.com.crt /etc/docker/certs.d/harbor.entorno.com/harbor.entorno.com.crt
